name: Bug report
description: Report a reproducible defect in trspecfit.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug.
        For usage questions, open a Discussion in Q&A instead.
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-checks
      options:
        - label: I searched existing issues and discussions.
          required: true
        - label: I can reproduce this with a minimal example.
          required: true
  - type: input
    id: version
    attributes:
      label: trspecfit version
      placeholder: e.g. 0.4.3
    validations:
      required: true
  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: e.g. 3.12.2
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g. Ubuntu 24.04
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Minimal reproduction
      description: Include code, YAML, and steps needed to reproduce.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Traceback / logs
      render: shell
    validations:
      required: false
