name: Feature request
description: Propose a trackable feature for trspecfit.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        For early-stage brainstorming, open a Discussion in Ideas first.
        Use this template when the request is concrete enough to track.
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-checks
      options:
        - label: I searched existing issues and discussions.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What scientific or workflow pain point should this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe API, behavior, or UX if known.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
  - type: textarea
    id: success
    attributes:
      label: Success criteria
      description: What outcome would indicate this feature is successful?
    validations:
      required: false
