# Project Configuration for trspecfit simulator

# Display settings (general verbosity)
show_info: 1  # 0: no output, 1: important, 2: all, 3+: debugging

# Axis labels
e_label: 'Energy (arb. units)' # x -> energy
t_label: 'Time (arb, units)' # y -> time
z_label: 'Intensity (arb. units)' # z -> intensity

# Plot settings
xdir: 'def'  # def(ault) or rev(erse)
xtype: 'lin'  # lin or log
ydir: 'def'  # def(ault) or rev(erse)
ytype: 'lin'  # lin or log
zColorMap: 'viridis' # colormap in 2D plots
ztype: 'lin'  # lin or log (2D plots)
dpi_plt: 100 # figure display dpi
dpi_save: 300 # figure save dpi
res_mult: 5 # residual multiplier in figures

# File I/O settings
ext: '.dat'
fmt: '%.6e'
delim: ','
DA_fmt: '%04d'
DA_slices_fmt: '%06d'